In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
from sklearn.datasets import fetch_lfw_people
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np
import matplotlib.pyplot as plt

/Users/amlannag/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.cifar10.load_data()

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 29s 0us/step


In [18]:
print(type(X_train))

<class 'numpy.ndarray'>


In [20]:
# Calculate the mean and standard deviation for each channel

X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

X_train_tensor = tf.convert_to_tensor(X_train, dtype=tf.float32)
X_test_tensor = tf.convert_to_tensor(X_test, dtype=tf.float32)

mean = tf.reduce_mean(X_train_tensor, axis=(0, 1, 2))
std = tf.math.reduce_std(X_train_tensor, axis=(0, 1, 2))

# Convert to numpy arrays for easy viewing
mean_np = mean.numpy()
std_np = std.numpy()

print("Mean of each channel (R, G, B):", mean_np)
print("Standard deviation of each channel (R, G, B):", std_np)

Mean of each channel (R, G, B): [0.32768 0.32768 0.32768]
Standard deviation of each channel (R, G, B): [0.27755317 0.26929596 0.26811677]


In [14]:
samples, height, width, chalens = X_train.shape

In [15]:
categories = len(np.unique(y_train))
y_train_cat = to_categorical(y_train, categories)
y_test_cat = to_categorical(y_test, categories)
print(y_test_cat)
print(categories)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]
10


In [16]:
inputs = Input(shape=(height,width,chalens))
net1 = Conv2D(filters = 32, kernel_size = (3,3), padding="same", activation="relu")(inputs)
pool1 = MaxPooling2D(pool_size=(2,2))(net1)
net2 = Conv2D(filters = 32, kernel_size = (3,3), padding="same", activation="relu")(pool1)
pool2 = MaxPooling2D(pool_size=(2,2))(net2)
flat = Flatten()(pool2)
net3 = Dense(128, activation="relu")(flat)
output = Dense(categories, activation="softmax")(net3)

In [17]:
model = Model(inputs, output)

model.compile(optimizer= tf.keras.optimizers.Adam(learning_rate=0.01), loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train_cat,
                epochs=10,
                batch_size=1000,
                shuffle=True,
                validation_data=(X_test, y_test_cat))

Epoch 1/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 22s 412ms/step - accuracy: 0.1053 - loss: 75.4737 - val_accuracy: 0.0999 - val_loss: 2.3027
Epoch 2/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 24s 477ms/step - accuracy: 0.1015 - loss: 2.3026 - val_accuracy: 0.1000 - val_loss: 2.3027
Epoch 3/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 23s 468ms/step - accuracy: 0.0974 - loss: 2.3029 - val_accuracy: 0.0999 - val_loss: 2.3026
Epoch 4/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 23s 468ms/step - accuracy: 0.0992 - loss: 2.3027 - val_accuracy: 0.1000 - val_loss: 2.3026
Epoch 5/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 24s 488ms/step - accuracy: 0.1002 - loss: 2.3027 - val_accuracy: 0.1000 - val_loss: 2.3027
Epoch 6/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 23s 470ms/step - accuracy: 0.0987 - loss: 2.3027 - val_accuracy: 0.1000 - val_loss: 2.3027
Epoch 7/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 24s 478ms/step - accuracy: 0.1007 - loss: 2.3027 - val_accuracy: 0.0999 - val_loss: 2.3027
Epoch 8/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 25s 493ms/step - accuracy: 0.1020 - loss: 2.3026 - val_acc